version: '3'
services:
  spring-boot-rest-api-app:
      image: transaction
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      volumes:
        - /data/spring-boot-app
